source 'https://rubygems.org'

gem 'byebug'
gem 'cucumber'
gem 'faker'
gem 'nokogiri', '~> 1.8.5'
gem 'rake'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rspec'
gem 'watir'
gem 'webdrivers', '~> 3.0'
